# mysql은 AWS RDS에서 프로비전하고 나머지를 사용하는 compose 파일

services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: T2rOqyU9IG
#      MYSQL_DATABASE: ecommerce_db
#    volumes:
#      - mysql-data:/var/lib/mysql
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

#  jenkins:
#    image: jenkins/jenkins:lts
#    container_name: jenkins
#    privileged: true
#    user: root
#    ports:
#      - "9090:8080"
#      - "50000:50000"
#    volumes:
#      - jenkins_home:/var/jenkins-home
#      - /var/run/docker.sock:/var/run/docker.sock # Docker 데몬과 통신
#      - /usr/bin/docker:/usr/bin/docker # Jenkins에서 Docker CLI 사용
#    restart: always

volumes:
#  mysql-data:
  redis-data:
#  jenkins_home:
