# 테스트 컨테이너 사용으로 하위 설정은 무시됨
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://ecommerce.cx6kge0eeual.ap-northeast-2.rds.amazonaws.com:3306/ecommerce_db
    username: root
    password: T2rOqyU9IG
    driver-class-name: com.mysql.cj.jdbc.Driver

